# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = ch02-sysinfo
DESTDIR = ../x64/Debug
CONFIG += debug
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += debug
UI_DIR += GeneratedFiles
RCC_DIR += GeneratedFiles

QT += core gui charts
CONFIG += C++14
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

HEADERS += ./SysInfo.h \
    ./ch02sysinfo.h \
    CpuWidget.h \
    MemoryWidget.h \
    SysInfoWidget.h


SOURCES += ./SysInfo.cpp \
    ./ch02sysinfo.cpp \
    ./main.cpp\
    CpuWidget.cpp \
    MemoryWidget.cpp \
    SysInfoWidget.cpp

    
windows {
    SOURCES += SysInfoWindowsImpl.cpp
    HEADERS += SysInfoWindowsImpl.h
}

linux {
    SOURCES += SysInfoLinuxImpl.cpp
    HEADERS += SysInfoLinuxImpl.h
}
macx {
    SOURCES += SysInfoMacImpl.cpp
    HEADERS += SysInfoMacImpl.h
}


FORMS += ./ch02sysinfo.ui
RESOURCES += ch02sysinfo.qrc
